---
- name: Upgrade the system
  apt:
    update_cache: true
    upgrade: dist
  register: apt_cache
  retries: 50
  until: apt_cache is success
  when: common_upgrade == true

- name: Install system required packages
  apt:
    pkg:
      - ntp
      - python3
      - python3-pip
      - python3-apt
      - vim-nox
      - curl
      - apt-transport-https
      - software-properties-common
      - haveged  

- name: Install basic utils
  apt:
    state: present
    pkg:
      - vim-nox
      - curl
      - htop
      - mtr-tiny
      - sendmail
      - mailutils
  when: common_basic == true

- name: Set timezone
  timezone:
    name: "{{ common_timezone }}"
  when: common_timezone is defined
